version: '3'
services:
  nextjs-app:
    container_name: nextjs-container
    build: .
    ports:
      - "${HOST_PORT:-8081}:3000"
    volumes:
      - ./eis-tracker/database:/database
      - ./eis-tracker/public/photos:/public/photos
    environment:
      - NODE_ENV=production
    restart: unless-stopped