version: '3.8'

services:
  nextjs-app:
    container_name: nextjs-container
    build: .
    ports:
      - "${HOST_PORT:-8081}:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - db

  db:
    container_name: mysql-container
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-nextjsdb}"
      MYSQL_USER: "${MYSQL_USER:-nextjsuser}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-password}"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
